# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'InternshipSSoft#1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for InternshipSSoft#1

end
